version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1
    environment:
      CODACY_PROJECT_TOKEN: ebcca75223d44c4cbeda90fa9b3e7b5a
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install
      - run:
          name: run tests
          command: |
            bundle exec rspec
      - run:
          name: run code analyzer
          command: |
            bundle exec rubocop
