version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1
    environment:
      CODACY_PROJECT_TOKEN: a787dc401ce74569978ff206a4064544
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install
      - run:
          name: run tests
          command: |
            bundle exec rspec
      - run:
          name: run code analyzer
          command: |
            bundle exec rubocop
